### ISSUE TITLE
How to upload on apache centOS server using HTTPS? 

### ISSUE THREAD

**Issue by ashishnimrot** [LaravelDaily/Laravel-CoreUI-AdminPanel#1]
I am trying to upload local php artisan serve to domain server by renaming server.php -> index.php and copy .htaccess public -> root .

Finally Show This page isn’t working domain.domain.net is currently unable to handle this request.
HTTP ERROR 500

**Comment by PovilasKorop** [comment]
@ashishnimrot sorry you're doing something really non-standard. First, I would not use "artisan serve" server for any real project, instead use Homestead/Valet. Second, why you upload files, you should have dedicated server, SSH there and do "git pull".

Some of the articles I've written in the past about it:
- https://laraveldaily.com/what-server-is-needed-to-deploy-laravel-projects/
- https://laraveldaily.com/how-to-deploy-laravel-projects-to-live-server-the-ultimate-guide/

If you have shared-hosting or other non-standard environment, sorry we can't help you with advice.
