### ISSUE TITLE
No RTL ?

### ISSUE THREAD

**Issue by mohamedmoussasoli** [LaravelDaily/Laravel-CoreUI-AdminPanel#3]
does it support RTL ?

**Comment by PovilasKorop** [comment]
@reactor123 we didn't do anything specific for RTL, so if it doesn't support out of the box then no.

**Comment by krishnamishra9026** [comment]
Now admin menu not working properly ca u fix this.

**Comment by PovilasKorop** [comment]
@krishnamishra9026 already fixed this morning, in these commits: https://github.com/LaravelDaily/Laravel-CoreUI-AdminPanel/commit/5c6abf30aef4b2a844a46b1a528e41f9064cfcbe https://github.com/LaravelDaily/Laravel-CoreUI-AdminPanel/commit/e21526f40cfdbdce0ce99e5cf39def75c7eddc27

Please pull latest changes.

And next time, please create a NEW issue and not comment on other ones.
