### ISSUE TITLE
Authentication Error/Message Issues

### ISSUE THREAD

**Issue by colsieb** [LaravelDaily/Laravel-CoreUI-AdminPanel#4]
No errors or feedback seem to be shown on login authentication failures and operations.

- On email verification check failure for password reset It errors out with:
**'Array to string conversion'**:

> Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
> :39
> C:\Users\systems\Documents\WFH Stuff\sys-dev1\coreui\vendor\laravel\framework\src\Illuminate\Support\MessageBag.php

Incorrect password messages also don't show on login although the actual login works fine. I have had a crack at figuring this out but I am not yet experienced enough :-)

Wndows7
Xampp3.22 / PHP7.25 / Laravel 6.0.1

**Comment by Marius-K** [comment]
Hello @colsieb 

Thank you for noticing this bug. I've fixed this issue in commit e9036b5, so pull the latest code from repository or make changes from commit by yourself. :)
