### ISSUE TITLE
Scrolling left menu

### ISSUE THREAD

**Issue by Lucekvip** [LaravelDaily/Laravel-CoreUI-AdminPanel#6]
Hi, first I want to thank you for great job with this project. I've some problem with scrolling sidebar in left menu even on clear project pulled from github. Bar is showing up on mouse move but not scrolling menu. I've duplicated extra positions in menu to make it longer, checked on Firefox, Chrome and Edge but the same result. Some sugestions?

**Comment by PovilasKorop** [comment]
@Lucekvip can you attach a screenshot or short video screencast what do you mean exactly by scrolling menu?

**Comment by Lucekvip** [comment]
Yes of course, I hope this will help
![AdminPanel](https://user-images.githubusercontent.com/51164544/87391381-e4aee200-c5aa-11ea-8e1d-421c0f263210.png)

**Comment by PovilasKorop** [comment]
@Lucekvip interesting... Unfortunately, I don't have a quick solution here, because this free project is based on CoreUI 2 which is their older version and we don't do much work with that anymore.

So maybe someone on our team may take a look at the reason, but realistically, only in a few weeks, cause we're in a holiday season at the moment.

**Comment by Lucekvip** [comment]
Ok.  I've finaly solved that problem so maby it will be helpfull for others, that's what I did:

1. In layouts\admin.blade.php need to add one more script tag to perfect-scrollbar before coreui
`<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar/1.1.0/perfect-scrollbar.min.js"></script>`

2. In partials\menu.blade.php need to remove code below, otherwise there will be doubled bar one moving properly and the other not.
`<div class="ps__rail-x" style="left: 0px; bottom: 0px;">
            <div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div>
        </div>
        <div class="ps__rail-y" style="top: 0px; height: 869px; right: 0px;">
            <div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 415px;"></div>
        </div>`
